version: '3.7'
services:
  pgpool:
    image: smirart/pgpool:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pgpool.conf:/etc/pgpool/pgpool.conf
  pg0:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=password
